### ISSUE TITLE
The python binding doesn't install itself

### ISSUE THREAD

**Issue by yurivict** [wassimj/Topologic#34]
```
===>   Generating temporary packing list
ninja: error: unknown target 'install/strip'
*** Error code 1
```

**Comment by wassimj** [comment]
Sorry I need more information. Is this on Linux?

**Comment by yurivict** [comment]
This is on FreeBSD.

**Comment by wassimj** [comment]
@brunopostle Are you able to help with this issue? Many thanks!

**Comment by brunopostle** [comment]
Yes, basically there is a minimal CMake build configuration that allows you to compile the Topologic C++ library and the pybind11 Python bindings as two separate steps. There is an install target for the library, but no integration with python packaging tools, so you have to install the bindings by copying the .so file into your PYTHONPATH.

This isn't ideal, but the project really needs somebody who understands cmake and python packaging to step up and fix it. The good news is that it isn't a particularly complex problem: the library is a pretty normal C++ shared library, and the python bindings are not doing anything weird either.

@wassimj I suggest adding a couple of 'labels' to this issue, in particular you should add: 'help wanted', 'cmake' and 'python'.

**Comment by sanzoghenzo** [comment]
Hi there,

I can try to look at this; I'm always scared when I have to build C/C++ code, but I have some experience in packaging python libraries.

Just for reference: the [pybind11 documentation](https://pybind11.readthedocs.io/en/stable/compiling.html) points to an [example using cmake](https://github.com/pybind/cmake_example); alternatively one can go with [setuptools](https://github.com/pybind/python_example) without the need to have pybind11 as submodule.

Being a python guy I'd prefer to use setuptools (it seems to be the recommended way), is it ok with you?

**Comment by wassimj** [comment]
Hi @sanzoghenzo Sure, thanks for your help.

**Comment by sanzoghenzo** [comment]
Hi there,
I'm sorry but my missing C++/CMake knowledge is a big obstacle in helping you with this.

What I got so far:

`pyproject.toml`

```toml
[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "pybind11>=2.8.0",
]

build-backend = "setuptools.build_meta"

[tool.cibuildwheel]
test-command = "python {project}/Python-Bindings/tests/topologictest01.py"
test-skip = "*universal2:arm64"
```

`setup.py`

```py
from glob import glob
from setuptools import setup

from pybind11.setup_helpers import Pybind11Extension, build_ext

__version__ = "0.0.1"

ext_modules = [
    Pybind11Extension(
        "topologic",
        sorted(glob("src/*.cpp")),
        include_dirs=[
            "include", 
            "../TopologicCore/include", 
            "/usr/include/opencascade", 
            "/usr/include/uuid"
        ],
        language='c++',
    ),
]

setup(
    name="topologic",
    version=__version__,
    author="Cardiff University and University College London",
    author_email="",
    url="https://github.com/wassimj/Topologic",
    description="Python bindings of Topologic",
    long_description="",
    ext_modules=ext_modules,
    cmdclass={"build_ext": build_ext},
    zip_safe=False,
    python_requires=">=3.6",
)
```

WIth this configuration the `include/pybind11` directory can be deleted, but I have 2 problems:

1 - the opencascade and uuid include paths are hardcoded, I didn't find any mentions in pybind11's documentation on how to make them auto-discoverable
2 - If I run `pip install -e .` the build process stops at 

```
src/Attribute.cppwg.cpp: In member function ‘virtual void* Attribute_Overloads::Value()’:
    /tmp/pip-build-env-lag9ihzd/overlay/lib/python3.10/site-packages/pybind11/include/pybind11/pybind11.h:2760:57: error: void value not ignored as it ought to be
     2760 |             return pybind11::detail::cast_safe<ret_type>(std::move(o));                           \
          |                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~
    /tmp/pip-build-env-lag9ihzd/overlay/lib/python3.10/site-packages/pybind11/include/pybind11/pybind11.h:2794:9: note: in expansion of macro ‘PYBIND11_OVERRIDE_IMPL’
     2794 |         PYBIND11_OVERRIDE_IMPL(PYBIND11_TYPE(ret_type), PYBIND11_TYPE(cname), name, __VA_ARGS__); \
          |         ^~~~~~~~~~~~~~~~~~~~~~
    /tmp/pip-build-env-lag9ihzd/overlay/lib/python3.10/site-packages/pybind11/include/pybind11/pybind11.h:2832:5: note: in expansion of macro ‘PYBIND11_OVERRIDE_PURE_NAME’
     2832 |     PYBIND11_OVERRIDE_PURE_NAME(                                                                  \
          |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
    /tmp/pip-build-env-lag9ihzd/overlay/lib/python3.10/site-packages/pybind11/include/pybind11/pybind11.h:2858:5: note: in expansion of macro ‘PYBIND11_OVERRIDE_PURE’
     2858 |     PYBIND11_OVERRIDE_PURE(PYBIND11_TYPE(ret_type), PYBIND11_TYPE(cname), fn, __VA_ARGS__);
          |     ^~~~~~~~~~~~~~~~~~~~~~
    src/Attribute.cppwg.cpp:16:9: note: in expansion of macro ‘PYBIND11_OVERLOAD_PURE’
       16 |         PYBIND11_OVERLOAD_PURE(
          |         ^~~~~~~~~~~~~~~~~~~~~~
    error: command '/usr/bin/gcc' failed with exit code 1
    [end of output]
```

For this I didn't find a solution using my google-fu, and I'm sure that there will be many more problems after this... I already spent too much time and I have to give up on this!

**Comment by brunopostle** [comment]
I see this last error on the fedora 37 build host, but not on fedora 36.

They both have GCC 12.1.1, but the difference seems to be an upgrade from pybind11 2.9.2 to pybind11 2.10.0

@sanzoghenzo what version of pybind11 do you have?

```
/src/Attribute.cppwg.cpp:16:9: error: void value not ignored as it ought to be
   16 |         PYBIND11_OVERLOAD_PURE(
      |         ^~~~~~~~~~~~~~~~~~~~~~
```

**Comment by sanzoghenzo** [comment]
@brunopostle great catch, using `pybind11==2.9.2` in the `pyproject.toml` solves this particular issue...

But, as I suspected, another one came up...

```
    In file included from ../TopologicCore/include/Wire.h:19,
                     from include/wrapper_header_collection.hpp:9:
    ../TopologicCore/include/Topology.h: In instantiation of ‘void TopologicCore::Topology::Navigate(const Ptr&, std::__cxx11::list<std::shared_ptr<_Tp> >&) const [with Subclass = TopologicCore::Topology; Ptr = std::shared_ptr<TopologicCore::Topology>]’:
    src/Topology.cppwg-Modified.cpp:472:29:   required from here
    ../TopologicCore/include/Topology.h:814:35: error: ‘Type’ is not a member of ‘TopologicCore::Topology’
      814 |                 if (Subclass::Type() > GetType())
          |                     ~~~~~~~~~~~~~~^~
    ../TopologicCore/include/Topology.h:825:40: error: ‘Type’ is not a member of ‘TopologicCore::Topology’
      825 |                 else if (Subclass::Type() < GetType())
          |                          ~~~~~~~~~~~~~~^~
    error: command '/usr/bin/gcc' failed with exit code 1
```

I now realize that going the setuptools way is not a good strategy because it completely ignores the CMake files.
The "best" way should be using the [`scikit-build` example](https://github.com/pybind/scikit_build_example), as suggested by the cmake example I linked above.
I'll try this one before giving up :wink:

**Comment by brunopostle** [comment]
> @brunopostle great catch, using `pybind11==2.9.2` in the `pyproject.toml` solves this particular issue...

This is probably still a bug in Topologic, i.e. it needs to be fixed to work with pybind11 2.10.0

**Comment by wassimj** [comment]
I may be wrong, but this kind of bug ('Type' is not a member of 'TopologicCore::Topology' would have failed with gcc regardless of pybind. The fact that Topologic builds the C++ code successfully tells me there is something else going on here. Now it could be that the cppwg files are buggy. I will have to look deeper into that.

**Comment by brunopostle** [comment]
On Tue, 9 Aug 2022, 15:06 Andrea Ghensi, wrote:

> ImportError: libTopologicCore.so.0: cannot open shared object file: No such file or directory
>
> And here I remembered why I "hate" C/C++ 🤣
> This is where I really give up.
>
This is more or less expected, Linux won't import a dynamic library unless
it is in an approved location (basically /usr/lib64/), specified in the
environment using LD_LIBRARY_PATH, or manipulated using rpath.

I.e. do this before your test:

    export LD_LIBRARY_PATH=/folder/where/library/gets/installed

>

**Comment by sanzoghenzo** [comment]
yeh, well, the whole point of having a proper python package, for me, was to avoid fiddling with paths and the like...

As I said, I'm no expert at all at C++/CMake, so I'll leave it to you, if you think this is worth the effort.

**Comment by brunopostle** [comment]
On Tue, 9 Aug 2022, 16:33 Andrea Ghensi, wrote:

> yeh, well, the whole point of having a proper python package, for me, was
> to avoid fiddling with paths and the like...
>
I don't know how this is normally resolved. I have had this problem before
with packages installed with setup.py, I ended up installing as root to
force a findable installation location.

Maybe libTopologicCore can be built as a static library, and the python
bindings can include it.

>

**Comment by wassimj** [comment]
This has now all been resolved by the new cmake refactoring and the new pybind version.
